version: '3.9'
services:
  database:
    image: mysql:8.0-debian
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - '127.0.0.1:8888:80'